CUDA is available: True
Using 4 GPUs for model parallelization.
Traceback (most recent call last):
  File "/home/usuaris/imatge/joan.manel.cardenas/age_predictions/input_data.py", line 129, in <module>
    model = DDP(model, device_ids=[dist.get_local_rank()], output_device=dist.get_local_rank())
TypeError: DistributedSampler.__init__() got an unexpected keyword argument 'device_ids'
Creating DDP model for rank 0 GPU